
# Creating this compose file to build all images and run all containers
# in on go.
version: '3.8'
services:
  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    environment:
      DISCOVERY_SERVER: eureka-service
    depends_on:
      - eureka-service
    ports:
      - "8081:8080"
  mysql:
    image: mysql
    container_name: mysql_restaurant_db
    restart: always
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Welcome#123
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: Welcome#123
    volumes:
      - mysql_data:/var/lib/mysql
  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    environment:
      DISCOVERY_SERVER: eureka-service
      DB_USER_NAME: restaurant_user
      DB_PASSWORD: Welcome#123
      DB_HOST: mysql_restaurant_db
      DB_PORT: 3306
      DB_NAME: restaurant_db
    depends_on:
      - eureka-service
      - gateway-service
      - mysql
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DISCOVERY_SERVER: eureka-service
      DB_USER_NAME: restaurant_user
      DB_PASSWORD: Welcome#123
      DB_HOST: mysql_restaurant_db
      DB_PORT: 3306
      DB_NAME: restaurant_db
    depends_on:
      - eureka-service
      - gateway-service
      - mysql
volumes:
  mysql_data: